table_model_mapping = {
    'ffz_users': {'app':'ffzusers', 'model':'User', 'filters':{'date_filter':True, 'filter_list':['user_signup_date']}},
    'ffz_manufactures': {'app': 'farmers', 'model': 'Farmers', 'filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_manufacture_vegitables': {'app': 'farmers', 'model': 'FarmersVeg','filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_stores': {'app': 'locations' , 'model': 'Store', 'filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_category': {'app': 'products', 'model':'Categories', 'filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_vegitables': {'app': 'products', 'model':'Products', 'filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_main_city': {'app':'locations', 'model':'City','filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_orders': {'app':'orders' ,'model':'Order','filters':{'date_filter':True, 'filter_list':['order_date']}},
    'ffz_user_address': {'app':'locations', 'model':'Address','filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_store_zip_codes': {'app':'locations', 'model':'ZipCodes','filters':{'date_filter':True, 'filter_list':['store_zip_code_added_date']}},
    'ffz_placed_orders': {'app':'orders', 'model':'PlacedOrders','filters':{'date_filter':True, 'filter_list':['placed_order_date']}},
    'ffz_delivery_zip_code_mapping': {'app':'locations', 'model':'ZipMapping','filters':{'date_filter':True, 'filter_list':['zip_dp_added_date']}},
    'ffz_transaction_before': {'app':'payments', 'model':'TransactionBefore','filters':{'date_filter':True, 'filter_list':['bf_tran_date']}},
    'ffz_cod_transaction': {'app':'payments', 'model':'CODTransactions','filters':{'date_filter':True, 'filter_list':['cod_trans_date']}},
    'ffz_promos': {'app':'offers', 'model':'Promos','filters':{'date_filter':True, 'filter_list':['promo_start_date']}},
    'ffz_user_promos': {'app':'offers', 'model':'UserPromos','filters':{'date_filter':True, 'filter_list':['user_promo_added_time']}},
    'ffz_razor_payment_history': {'app':'payments', 'model':'Razorpay','filters':{'date_filter':True, 'filter_list':['create_date']}},
    'ffz_veg_inventory': {'app':'inventory', 'model':'Inventory','filters':{'date_filter':True, 'filter_list':['modify_date']}},
    'farmer_reg': {'app':'farmers','model': 'Farmer_Reg','filters':{'date_filter':False, 'filter_list':[]}},
    'farmer_tests': {'app':'farmers', 'model':'Farmer_Test','filters':{'date_filter':True, 'filter_list':['f_test_date']}},
    'ffz_user_review': {'app':'common', 'model':'Review','filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_sub_v2_delivery_date': {'app':'common', 'model':'SubV2DeliveryDate','filters':{'date_filter':True, 'filter_list':['sub_delivery_date']}},
    'ffz_user_popularsearch': {'app':'products', 'model':'UserPopularSearches','filters':{'date_filter':True, 'filter_list':['created_on']}},
    'ffz_recommended_products': {'app':'products', 'model':'RecommendedProducts','filters':{'date_filter':True, 'filter_list':['last_updated_on']}},
    'ffz_inventory_log': {'app':'inventory', 'model':'InventryLog','filters':{'date_filter':True, 'filter_list':['inventory_added_date']}},
    'ffz_user_cashback': {'app':'offers', 'model':'UserCashback','filters':{'date_filter':False, 'filter_list':[]}},
    'ffz_user_referral': {'app':'offers', 'model':'UserReferral','filters':{'date_filter':True, 'filter_list':['referral_date']}},
    'ffz_placed_order_cancel_history': {'app':'orders', 'model':'CancelledOrders','filters':{'date_filter':True, 'filter_list':['modify_date']}},
    'ffz_veg_price': {'app':'products', 'model':'VegetablePrice','filters':{'date_filter':True, 'filter_list':['veg_price_modify_date']}},
    'razor_payment_history': {'app':'payments', 'model':'RazorPaymentHistory','filters':{'date_filter':False, 'filter_list':[]}}

}