# Generated by Django 3.2.6 on 2021-12-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ffzuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ffzuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
